DEBUGFLAGS = -g -O2
CC = clang
# Should be clang if no cc in system
CFLAGS = -Wall -W -pedantic
VERSION = 0.7.34
DISTFILE = list-$(VERSION).tar.gz
DISTBINFILE = list-bin-$(VERSION).tar.gz
#SRCDIR = list-$(VERSION)
SRCDIR = src
LDFLAGS = -s
LIBS = -lcurses
OPTFLAGS = -O3 -fcommon

OBJECTS = list.o dequeue.o bugwrite.o screen.o file.o input.o
DOBJECTS = listd.o dequeued.o bugwrited.o screend.o filed.o inputd.o

all: list

debug: list_d

.c.o:
	$(CC) $(CFLAGS) $(OPTFLAGS) -c $<

$(DOBJECTS): %d.o: %.c
	$(CC) $(DEBUGFLAGS) $(CFLAGS) -c $< -o $@

list: $(OBJECTS)
	$(CC) $(LDFLAGS) -o list $(OBJECTS) $(LIBS)

list_d: $(DOBJECTS)
	$(CC) -o list_d $(DOBJECTS) $(LIBS)

#list_static:
#	$(CC) $(LDFLAGS) -static -o list_static $(OBJECTS) $(LIBS)

install:
	install -m755 list /usr/local/bin/list
	install -m644 list.1 /usr/local/man/man1/list.1

dist: list.c screen.c file.c input.c list.h
	cd .. && tar czvf $(DISTFILE) LICENSE README.md $(SRCDIR)/BSDMakefile $(SRCDIR)/ChangeLog $(SRCDIR)/Makefile $(SRCDIR)/TODO.txt $(SRCDIR)/bugwrite.c $(SRCDIR)/dequeue.c $(SRCDIR)/dequeue.h $(SRCDIR)/file.c $(SRCDIR)/filebrowse.c $(SRCDIR)/input.c $(SRCDIR)/list.1 $(SRCDIR)/list.c $(SRCDIR)/list.h $(SRCDIR)/screen.c

dist-bin: list list_d # list_static
	cd .. && tar czvf $(DISTBINFILE) LICENSE README.md $(SRCDIR)/list $(SRCDIR)/list_d $(SRCDIR)/list.1
#removed $(SRCDIR)/list_static as we can't make it on linux, haven't checked on {Free,Net,Open)BSD

clean:
	rm -f *.o list list_d

uninstall:
	rm /usr/local/bin/list
	rm /usr/local/man/man1/list.1
