DEBUGFLAGS = -g -O2
CC = wcc
CL = wlink
CFLAGS = -bc -wx -d3
VERSION = 0735
DISTFILE = list$(VERSION).tgz
DISTBINFILE = lstb$(VERSION).tgz
SRCDIR = src
INCDIR = c:\pdcurses
LDFLAGS = 
LIBS = pdcurses.lib
OPTFLAGS = -od

OBJECTS = list.obj dequeue.obj bugwrite.obj file.obj input.obj showhelp.obj screen.obj

all: list.exe

.c.obj:
	$(CC) $(CFLAGS) $(OPTFLAGS) -i=$(INCDIR) -fo=$@ $<

list.exe: $(OBJECTS)
	$(CL) $(LDFLAGS) @list.lnk

clean:
	del *.obj list.exe
